# azure-pipelines.yml
trigger:
  branches:
    include:
      - develop
      - master
    exclude:
      - feature/*
      - hotfix/*
pr:
  branches:
    include:
      - develop
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.9'
  functionAppName: 'etl-poc-function'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python $(pythonVersion)'

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install dependencies'

          - script: |
              pip install pytest pytest-cov flake8
              flake8 src/
              pytest tests/ --cov=src --cov-report=xml
            displayName: 'Lint and Run tests'

  - stage: Deploy_Dev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    jobs:
      - job: Deploy
        steps:
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: 'Your-Azure-Subscription'
              appName: '$(functionAppName)-dev'
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'

  - stage: Deploy_Prod
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: Deploy
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@1
                  inputs:
                    azureSubscription: 'Your-Azure-Subscription'
                    appName: '$(functionAppName)-prod'
                    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
