trigger:
  branches:
    include:
      - develop
    exclude:
      - feature/*
      - hotfix/*

pr:
  branches:
    include:
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'
  webAppName: 'etl-poc-webapp'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python $(pythonVersion)'

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install dependencies'

          - script: |
              pip install pytest pytest-cov flake8
              flake8 src/
            displayName: 'Lint and Run tests'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(webAppName).zip'
              replaceExistingArchive: true
            displayName: 'Create deployment package'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'
            displayName: 'Publish artifacts'

  - stage: Deploy_Dev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    jobs:
      - deployment: Deploy
        environment: development
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: 'drop'
                  
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'sc_azure_etl_poc'
                    appName: '$(webAppName)-dev'
                    package: '$(Pipeline.Workspace)/drop/$(webAppName).zip'