trigger:
  branches:
    include:
      - develop
    exclude:
      - feature/*
      - hotfix/*

pr:
  branches:
    include:
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'
  #webAppName: 'etl-poc-web'
  webAppName: 'etl-poc-web'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - checkout: self
            
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python $(pythonVersion)'

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install dependencies'

          - script: |
              pip install pytest pytest-cov flake8
              flake8 src/
              pytest tests/ --cov=src --cov-report=xml
            displayName: 'Lint and Run tests'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/src'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(functionAppName).zip'
              replaceExistingArchive: true
            displayName: 'Create deployment package'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'
            displayName: 'Publish artifacts'

  - stage: Deploy_Dev
    jobs:
      - deployment: Deploy
        environment: development
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: 'drop'
                  
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'sc_azure_etl_poc'
                    appName: '$(fwebAppName)'
                    package: '$(Pipeline.Workspace)/drop/$(functionAppName).zip'